service:
  name: notification-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: sa-east-1
  iamRoleStatements: 
    - ${file(iam/sendMailIAM.yml):SendMailIAM}
  
functions:
  sendMail:
    handler: src/handlers/sendMail.handler